# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edcecfa1df8262c05de4b2e2db38a8319724d9c07372fd1025dcef22422087e4193ba2095cedcc012c1619500c10bdfa8489c64a0060125188370387bffa73c4

test:
  secret_key_base: cc6dba632fc392c4ff1417e786cb6d3208d26ae12fc45579d6b3bed92f75318fe213a0c32282a5fe0da76d762ad01a66188ca6d3266a73fabecebc06ad6f68b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
